version: '3'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db
      - phpmyadmin

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db
      - phpmyadmin

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: tareas
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - laravel

networks:
  laravel:
